"""add phone_e164 to users

Revision ID: 9056094ac1f5
Revises: 5d2c4d69cf85
Create Date: 2025-08-08 12:06:41.768052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9056094ac1f5'
down_revision = '5d2c4d69cf85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_e164', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_e164')

    # ### end Alembic commands ###
